# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Amber Warren
email: amber.warren@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Amber Warren is expert in English language learning and education.
twitter_username: username
#github_username: amber-warren
minimal_mistakes_skin: sunrise
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#link: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-pdf-embed


  # This is the stuff on the left of the home page
author:
  name   : "Amber Warren"
  avatar : "/assets/images/amber-warren.jpg"
  bio    : "English language learning and qualitative research specialist."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ambernwarren"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amber-warren"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ambernwarren"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/amber-warren"
      
defaults:
  # _posts
  # - scope:
  #     path: ""
  #     type: posts
  #   values:
  #     layout: single
  #     author_profile: true
  #     read_time: true
  #     comments: true
  #     share: true
  #     related: true
  # _pages

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# category_archive:
#   type: liquid
#   path: /categories/
head_scripts: 
  - https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.8.335/pdf.min.js
  
tag_archive:
  type: liquid
  path: /tags/

theme: jekyll-theme-modernist